//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.27 at 08:11:57 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://datex2.eu/schema/1_0/1_0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.datex2.schema._1_0._1_0;
